const products = [
    {
      id: 1,
      name: 'Basic Tee - Black',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Basic Tee in black.",
      price: '$35',
      color: 'Black',
    },
    {
      id: 2,
      name: 'Classic Hoodie - Gray',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-02.jpg',
      imageAlt: "Front of men's Classic Hoodie in gray.",
      price: '$50',
      color: 'Gray',
    },
    {
      id: 3,
      name: 'Casual Joggers - Navy',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-03.jpg',
      imageAlt: "Front of men's Casual Joggers in navy.",
      price: '$40',
      color: 'Navy',
    },
    {
      id: 4,
      name: 'Sports Sneakers - White',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-04.jpg',
      imageAlt: "Front of men's Sports Sneakers in white.",
      price: '$60',
      color: 'White',
    },
    {
        id: 5,
        name: 'Basic Tee - Black',
        href: '#',
        imageSrc: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
      },
      {
        id: 6,
        name: 'Classic Hoodie - Gray',
        href: '#',
        imageSrc: 'https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDN8fHxlbnwwfHx8fHw%3D',
        imageAlt: "Front of men's Classic Hoodie in gray.",
        price: '$50',
        color: 'Gray',
      },
      {
        id: 7,
        name: 'Casual Joggers - Navy',
        href: '#',
        imageSrc: 'https://plus.unsplash.com/premium_photo-1688497831503-235238709bd2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE2fHx8ZW58MHx8fHx8',
        imageAlt: "Front of men's Casual Joggers in navy.",
        price: '$40',
        color: 'Navy',
      },
      {
        id: 8,
        name: 'Sports Sneakers - White',
        href: '#',
        imageSrc: 'https://plus.unsplash.com/premium_photo-1690349404224-53f94f20df8f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE2fHx8ZW58MHx8fHx8',
        imageAlt: "Front of men's Sports Sneakers in white.",
        price: '$60',
        color: 'White',
      },
    {
        id: 9,
        name: 'Abstract Waves Painting',
        href: '#',
        imageSrc: 'https://images.unsplash.com/photo-1618331835717-801e976710b2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cGFpbnRpbmdzfGVufDB8fDB8fHww',
        imageAlt: 'Abstract painting with waves in blue.',
        price: '$200',
        color: 'Blue',
      },
      {
        id: 10,
        name: 'Sunset Landscape Painting',
        href: '#',
        imageSrc: 'https://images.unsplash.com/flagged/photo-1572392640988-ba48d1a74457?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGFpbnRpbmdzfGVufDB8fDB8fHww',
        imageAlt: 'Landscape painting capturing the beauty of a sunset.',
        price: '$250',
        color: 'Brown',
      },
      {
        id: 11,
        name: 'Vibrant Abstract Art',
        href: '#',
        imageSrc: 'https://images.unsplash.com/photo-1579167728798-a1cf3d595960?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHBhaW50aW5nc3xlbnwwfHwwfHx8MA%3D%3D',
        imageAlt: 'Vibrant abstract art with red and white stripes.',
        price: '$180',
        color: 'Red',
      },
      {
        id: 12,
        name: 'Green Nature Abstract',
        href: '#',
        imageSrc: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fHw%3D',
        imageAlt: 'Abstract painting inspired by green nature.',
        price: '$220',
        color: 'Green',
      },
  ];
  
  export default products;
  